# Generated by Django 4.1.5 on 2023-02-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0005_curso_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada_de_blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
